# Basic
title: neoesque
subtitle: Making Life Better
description: neoesque's Linux Blog
author: neoesque
author_title: 'Linux Admin'
avatar: css/images/avatar.png
location: 'Taipei, Taiwan'
follow: https://twitter/neoesque/
email: neoesque@gmail.com
language: zh-TW
timezone: Asia/Taipei

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.littlero.se
root: /
permalink: post/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - wedding/**

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: true # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
max_open_file: 100
filename_case: 0
highlight:
  enable: true
  backtick_code_block: true
  line_number: true
  tab_replace: '  '

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: false
  smartLists: true
  smartypants: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map: tags

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 1

# Server
port: 4000
logger: false
logger_format:

# Date / Time format
date_format: YYYY-MM-DD, ddd
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page


# Facebook
facebook:
  admins: 1573449527
  app_id: 163923413772109

# Extensions
plugins:
- hexo-generator-archive
- hexo-generator-feed
- hexo-generator-index
- hexo-generator-sitemap
- hexo-generator-tag
- hexo-generator-category
- hexo-renderer-ejs
- hexo-renderer-stylus
- hexo-renderer-marked
- hexo-renderer-pug
- hexo-renderer-swig
  #- hexo-generator-json-content
- hexo-server
- hexo-deployer-git
- hexo-generator-search
- hexo-symbols-count-time
- hexo-fs
  #- hexo-tag-instagram
  #- hexo-generator-amp


theme: next
exclude_generator:

font:
  enable: true
  global:
    size: 18

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true

search:
  path: search.xml
  field: post

# Deployment
deploy:
  type: git
  repository: git@github.com:neoesque/neoesque.github.com.git
  branch: master

# The following settings is the quick start options.
#generator_amp:
#  templateDir:  amp-template
#  assetDistDir: amp-dist
#  logo:
#    path:   sample/logo.png
#    width:  500
#    height: 60
#  substituteTitleImage:
#    path:   sample/sample-substituteTitleImage.png
#    width:  1024
#    height: 800
#  google_analytics: UA-37617901-1
#  warningLog: true   # If you want to validate, please set true.
